#! /usr/bin/env python


def build(bld):
    bld.program(
        source="parsing.cc",
        target="parsing",
        use='goat',
        cxxflags=['-fprofile-instr-generate', '-fcoverage-mapping'],
        ldflags='--coverage',
        includes="../src"
    )
